apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: sudharsan0007/node_docker_ex:latest  # Replace with your Docker image
        ports:
        - containerPort: 3000  # Updated to 3000
