apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  type: LoadBalancer  # Use NodePort if you're using Minikube
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80           # Port exposed to the outside
      targetPort: 3000   # Port your application is listening on
